version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.22.2/2022-01-31/bin/darwin/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - sudo mv ./aws-iam-authenticator /usr/local/bin/
      - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - mv ./kubectl /usr/local/bin/kubectl
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 578813437933.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t iaf .
      - docker tag iaf:latest 578813437933.dkr.ecr.us-east-1.amazonaws.com/iaf:latest
      - docker push 578813437933.dkr.ecr.us-east-1.amazonaws.com/iaf:latest
  post_build:
    commands:
      - echo "Fetching AWS credentials from CodeBuild environment"
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - aws eks --region us-east-1 update-kubeconfig  --name terraform-eks-demo
      - cat ~/.kube/config
      - aws sts get-caller-identity
      - kubectl config view --minify=true
      - kubectl delete deployment deployment-20489020 -n game-2048120
      - kubectl apply -f dsterra.yaml
      - kubectl apply -f ingress.yaml
